const deals=[
 {id:1,name:"Persil 3-in-1 Capsules, 50 Washes",retailer:"Tesco",category:"Household",price:7.50,was:12,saving:38,unit:"15p per wash",score:94,emoji:"🧺",loyalty:"Clubcard price",ends:"Ends 10 Sep",verified:"42 mins ago"},
 {id:2,name:"Lurpak Slightly Salted Butter 500g",retailer:"Sainsbury's",category:"Food & drink",price:4.25,was:6.75,saving:37,unit:"£8.50 per kg",score:92,emoji:"🧈",loyalty:"Nectar price",ends:"Ends 12 Sep",verified:"1 hr ago"},
 {id:3,name:"Pampers Baby-Dry Nappy Pants, 42 Pack",retailer:"Asda",category:"Baby",price:8.00,was:12,saving:33,unit:"19p each",score:89,emoji:"👶",loyalty:"",ends:"Ends 15 Sep",verified:"28 mins ago"},
 {id:4,name:"Aldi Ambiano 4.2L Air Fryer",retailer:"Aldi",category:"Home & kitchen",price:29.99,was:44.99,saving:33,unit:"Online & in store",score:88,emoji:"🍟",loyalty:"Specialbuy",ends:"While stocks last",verified:"2 hrs ago"},
 {id:5,name:"M&S Collection Colombian Coffee 227g",retailer:"M&S",category:"Food & drink",price:3.50,was:5,saving:30,unit:"£15.42 per kg",score:85,emoji:"☕",loyalty:"Sparks offer",ends:"Ends 11 Sep",verified:"55 mins ago"},
 {id:6,name:"Fairy Max Power Washing-Up Liquid 640ml",retailer:"Tesco",category:"Household",price:2.00,was:3.40,saving:41,unit:"£3.13 per litre",score:91,emoji:"🫧",loyalty:"Clubcard price",ends:"Ends 13 Sep",verified:"36 mins ago"},
 {id:7,name:"Taste the Difference Strawberries 400g",retailer:"Sainsbury's",category:"Food & drink",price:2.25,was:3.50,saving:36,unit:"£5.63 per kg",score:87,emoji:"🍓",loyalty:"Nectar price",ends:"Ends today",verified:"18 mins ago"},
 {id:8,name:"Nivea Sun Protect & Moisture SPF50 200ml",retailer:"Asda",category:"Health & beauty",price:5.50,was:9,saving:39,unit:"£2.75 per 100ml",score:90,emoji:"☀️",loyalty:"",ends:"Ends 14 Sep",verified:"1 hr ago"},
 {id:9,name:"Extra Special Italian Olive Oil 500ml",retailer:"Asda",category:"Food & drink",price:4.75,was:6.50,saving:27,unit:"£9.50 per litre",score:82,emoji:"🫒",loyalty:"Rewards price",ends:"Ends 16 Sep",verified:"1 hr ago"},
 {id:10,name:"Lacura Vitamin C Brightening Serum 30ml",retailer:"Aldi",category:"Health & beauty",price:4.99,was:7.99,saving:38,unit:"£16.63 per 100ml",score:86,emoji:"✨",loyalty:"Specialbuy",ends:"While stocks last",verified:"3 hrs ago"},
 {id:11,name:"M&S British Oakham Chicken 1.5kg",retailer:"M&S",category:"Food & drink",price:6.00,was:8.50,saving:29,unit:"£4.00 per kg",score:84,emoji:"🍗",loyalty:"Sparks offer",ends:"Ends 12 Sep",verified:"47 mins ago"},
 {id:12,name:"Tommee Tippee Closer to Nature Bottles",retailer:"Tesco",category:"Baby",price:10,was:17,saving:41,unit:"3 pack",score:93,emoji:"🍼",loyalty:"Clubcard price",ends:"Ends 17 Sep",verified:"31 mins ago"}
];
let activeRetailer="all",activeCategory="all",query="",visible=8;const saved=new Set(JSON.parse(localStorage.getItem("pdSaved")||"[]"));
const grid=document.getElementById("dealGrid"),empty=document.getElementById("emptyState"),load=document.getElementById("loadMore");
function filtered(){let list=deals.filter(d=>(activeRetailer==="all"||d.retailer===activeRetailer)&&(activeCategory==="all"||d.category===activeCategory)&&(!query||`${d.name} ${d.retailer} ${d.category}`.toLowerCase().includes(query)));const sort=document.getElementById("sortSelect").value;return list.sort((a,b)=>sort==="price"?a.price-b.price:sort==="saving"?b.saving-a.saving:b.score-a.score)}
function render(){const list=filtered();grid.innerHTML=list.slice(0,visible).map(d=>`<article class="deal-card"><div class="deal-img"><span>${d.emoji}</span><span class="retailer-pill">${d.retailer}</span><button class="save-btn ${saved.has(d.id)?"saved":""}" data-save="${d.id}" aria-label="Save ${d.name}">${saved.has(d.id)?"♥":"♡"}</button><span class="score"><i>${d.score}</i>/100</span></div><div class="deal-body"><div class="deal-meta"><span>${d.category}</span><span>Sample listing</span></div><h3>${d.name}</h3><div class="price-row"><span class="price">£${d.price.toFixed(2)}</span><span class="was">£${d.was.toFixed(2)}</span><span class="discount">-${d.saving}%</span></div><small class="unit">${d.unit}</small>${d.loyalty?`<div class="loyalty">★ ${d.loyalty}</div>`:""}<div class="card-footer"><span>Example: ${d.ends}</span><button class="view-deal" data-view="${d.id}">Preview →</button></div></div></article>`).join("");empty.hidden=list.length>0;load.hidden=list.length<=visible;document.getElementById("savedCount").textContent=saved.size}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
document.querySelectorAll(".retailer").forEach(b=>b.onclick=()=>{document.querySelectorAll(".retailer").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeRetailer=b.dataset.retailer;visible=8;render();document.getElementById("deals").scrollIntoView({behavior:"smooth"})});
document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{document.querySelectorAll(".category").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeCategory=b.dataset.category;visible=8;render()});
document.getElementById("searchForm").onsubmit=e=>{e.preventDefault();query=document.getElementById("searchInput").value.trim().toLowerCase();render();document.getElementById("deals").scrollIntoView({behavior:"smooth"})};
document.getElementById("searchInput").addEventListener("input",e=>{if(!e.target.value){query="";render()}});document.getElementById("sortSelect").onchange=render;
load.onclick=()=>{visible+=4;render()};document.getElementById("clearFilters").onclick=()=>{activeRetailer=activeCategory="all";query="";document.getElementById("searchInput").value="";document.querySelectorAll(".retailer,.category").forEach(x=>x.classList.toggle("active",x.dataset.retailer==="all"||x.dataset.category==="all"));render()};
grid.onclick=e=>{const save=e.target.closest("[data-save]"),view=e.target.closest("[data-view]");if(save){const id=+save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem("pdSaved",JSON.stringify([...saved]));toast(saved.has(id)?"Deal saved to your desk":"Deal removed from saved");render()}if(view)openDeal(+view.dataset.view)};
function openDeal(id){const d=deals.find(x=>x.id===id);document.getElementById("modalContent").innerHTML=`<div class="modal-product">${d.emoji}</div><h2 id="modalTitle">${d.name}</h2><p>This is an illustrative <strong>${d.retailer}</strong> listing showing how PoundDesk will present deal conditions.</p><div class="modal-detail"><div><small>Example price</small><strong>£${d.price.toFixed(2)}</strong></div><div><small>Sample score</small><strong>${d.score}/100</strong></div><div><small>Unit price</small><strong>${d.unit}</strong></div><div><small>Example expiry</small><strong>${d.ends}</strong></div></div><p class="affiliate-note">Preview only: this is not a live or verified offer. Retailer links will be enabled after approved affiliate feeds are connected. PoundDesk may then earn a commission from qualifying purchases at no extra cost to you.</p><button class="retailer-cta" id="retailerCta">Retailer links coming soon</button>`;document.getElementById("dealModal").hidden=false;document.body.style.overflow="hidden";document.getElementById("retailerCta").onclick=()=>toast("Retailer links will open when live feeds are connected")}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{document.getElementById("dealModal").hidden=true;document.body.style.overflow=""});document.addEventListener("keydown",e=>{if(e.key==="Escape"){document.getElementById("dealModal").hidden=true;document.body.style.overflow=""}});
document.getElementById("tryCompare").onclick=()=>toast("Full basket builder is planned for the live version");document.querySelector(".saved-trigger").onclick=()=>{activeRetailer=activeCategory="all";query="";visible=12;render();document.getElementById("deals").scrollIntoView({behavior:"smooth"});toast(saved.size?`${saved.size} saved deal${saved.size>1?"s":""} on your desk`:"Save a deal with the heart button")};document.getElementById("allRetailers").onclick=()=>toast("More retailers will be connected to the live data engine");
render();
